crawler:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  
  
  # Effort Controllers ---------------------------------------
  joint1_F_controller:
    type: effort_controllers/JointEffortController
    joint: joint1_F
  joint1_B_controller:
    type: effort_controllers/JointEffortController
    joint: joint1_B
  joint1_L_controller:
    type: effort_controllers/JointEffortController
    joint: joint1_L
  joint1_R_controller:
    type: effort_controllers/JointEffortController
    joint: joint1_R
  joint2_F_controller:
    type: effort_controllers/JointEffortController
    joint: joint2_F
  joint2_B_controller:
    type: effort_controllers/JointEffortController
    joint: joint2_B
  joint2_L_controller:
    type: effort_controllers/JointEffortController
    joint: joint2_L
  joint2_R_controller:
    type: effort_controllers/JointEffortController
    joint: joint2_R