crawler: #namespace

    #environment variables
    reward_height_b: 0.3
    reward_height_k: 10
    effort_penalty: 0.01    # penalty on reward
    effort_scale: 100     # increment in position for each command
    
    epoch_steps: 255
    running_step: 0.02 # amount of time the control will be executed
    
    